# Auto-generated extra verse data
EXTRA_WORDS = {
    '2:14': [
        ('وَإِذَا','wa-idhā','And when'),
        ('لَقُوا۟','laqū','they meet'),
        ('ٱلَّذِينَ','alladhīna','those who'),
        ('ءَامَنُوا۟','āmanū','believe[d]'),
        ('قَالُوٓا۟','qālū','they say'),
        ('ءَامَنَّا','āmannā','We believe[d]'),
        ('وَإِذَا','wa-idhā','But when'),
        ('خَلَوْا۟','khalaw','they are alone'),
        ('إِلَىٰ','ilā','with'),
        ('شَيَـٰطِينِهِمْ','shayāṭīnihim','their evil ones'),
        ('قَالُوٓا۟','qālū','they say'),
        ('إِنَّا','innā','Indeed, we'),
        ('مَعَكُمْ','maʿakum','(are) with you'),
        ('إِنَّمَا','innamā','only'),
        ('نَحْنُ','naḥnu','we'),
        ('مُسْتَهْزِءُونَ','mus\'tahziūna','(are) mockers'),
    ],
    '2:15': [
        ('ٱللَّهُ','al-lahu','Allah'),
        ('يَسْتَهْزِئُ','yastahzi-u','mocks'),
        ('بِهِمْ','bihim','at them'),
        ('وَيَمُدُّهُمْ','wayamudduhum','and prolongs them'),
        ('فِى','fī','in'),
        ('طُغْيَـٰنِهِمْ','ṭugh\'yānihim','their transgression'),
        ('يَعْمَهُونَ','yaʿmahūna','they wander blindly'),
    ],
    '2:16': [
        ('أُو۟لَـٰٓئِكَ','ulāika','Those'),
        ('ٱلَّذِينَ','alladhīna','(are) the ones who'),
        ('ٱشْتَرَوُا۟','ish\'tarawū','bought'),
        ('ٱلضَّلَـٰلَةَ','l-ḍalālata','[the] astraying'),
        ('بِٱلْهُدَىٰ','bil-hudā','for [the] guidance'),
        ('فَمَا','famā','So not'),
        ('رَبِحَت','rabiḥat','profited'),
        ('تِّجَـٰرَتُهُمْ','tijāratuhum','their commerce'),
        ('وَمَا','wamā','and not'),
        ('كَانُوا۟','kānū','were they'),
        ('مُهْتَدِينَ','muh\'tadīna','guided-ones'),
    ],
    '2:17': [
        ('مَثَلُهُمْ','mathaluhum','Their example'),
        ('كَمَثَلِ','kamathali','(is) like (the) example'),
        ('ٱلَّذِى','alladhī','(of) the one who'),
        ('ٱسْتَوْقَدَ','is\'tawqada','kindled'),
        ('نَارًۭا','nāran','a fire'),
        ('فَلَمَّآ','falammā','then, when'),
        ('أَضَآءَتْ','aḍāat','it illuminated'),
        ('مَا','mā','what'),
        ('حَوْلَهُۥ','ḥawlahu','(was) around him'),
        ('ذَهَبَ','dhahaba','took away'),
        ('ٱللَّهُ','l-lahu','Allah'),
        ('بِنُورِهِمْ','binūrihim','their light'),
        ('وَتَرَكَهُمْ','watarakahum','and left them'),
        ('فِى','fī','in'),
        ('ظُلُمَـٰتٍۢ','ẓulumātin','darkness[es]'),
        ('لَّا','lā','(so) not'),
        ('يُبْصِرُونَ','yub\'ṣirūna','(do) they see'),
    ],
    '2:18': [
        ('صُمٌّۢ','ṣummun','Deaf'),
        ('بُكْمٌ','buk\'mun','dumb'),
        ('عُمْىٌۭ','ʿum\'yun','blind'),
        ('فَهُمْ','fahum','so they'),
        ('لَا','lā','not'),
        ('يَرْجِعُونَ','yarjiʿūna','[they] will not return'),
    ],
    '2:19': [
        ('أَوْ','aw','Or'),
        ('كَصَيِّبٍۢ','kaṣayyibin','like a rainstorm'),
        ('مِّنَ','mina','from'),
        ('ٱلسَّمَآءِ','l-samāi','the sky'),
        ('فِيهِ','fīhi','in it (are)'),
        ('ظُلُمَـٰتٌۭ','ẓulumātun','darkness[es]'),
        ('وَرَعْدٌۭ','waraʿdun','and thunder'),
        ('وَبَرْقٌۭ','wabarqun','and lightning'),
        ('يَجْعَلُونَ','yajʿalūna','They put'),
        ('أَصَـٰبِعَهُمْ','aṣābiʿahum','their fingers'),
        ('فِىٓ','fī','in'),
        ('ءَاذَانِهِم','ādhānihim','their ears'),
        ('مِّنَ','mina','from'),
        ('ٱلصَّوَٰعِقِ','l-ṣawāʿiqi','the thunderclaps'),
        ('حَذَرَ','ḥadhara','(in) fear (of)'),
        ('ٱلْمَوْتِ ۚ','l-mawti','[the] death'),
        ('وَٱللَّهُ','wal-lahu','And Allah'),
        ('مُحِيطٌۢ','muḥīṭun','(is) [the One Who] encompasses'),
        ('بِٱلْكَـٰفِرِينَ','bil-kāfirīna','the disbelievers'),
    ],
    '2:20': [
        ('يَكَادُ','yakādu','Almost'),
        ('ٱلْبَرْقُ','l-barqu','the lightning'),
        ('يَخْطَفُ','yakhṭafu','snatches away'),
        ('أَبْصَـٰرَهُمْ ۖ','abṣārahum','their sight'),
        ('كُلَّمَآ','kullamā','Whenever'),
        ('أَضَآءَ','aḍāa','it flashes'),
        ('لَهُم','lahum','for them'),
        ('مَّشَوْا۟','mashaw','they walk'),
        ('فِيهِ','fīhi','in it'),
        ('وَإِذَآ','wa-idhā','and when'),
        ('أَظْلَمَ','aẓlama','it darkens'),
        ('عَلَيْهِمْ','ʿalayhim','on them'),
        ('قَامُوا۟ ۚ','qāmū','they stand (still)'),
        ('وَلَوْ','walaw','And if'),
        ('شَآءَ','shāa','had willed'),
        ('ٱللَّهُ','l-lahu','Allah'),
        ('لَذَهَبَ','ladhahaba','He would certainly have taken away'),
        ('بِسَمْعِهِمْ','bisamʿihim','their hearing'),
        ('وَأَبْصَـٰرِهِمْ ۚ','wa-abṣārihim','and their sight'),
        ('إِنَّ','inna','Indeed'),
        ('ٱللَّهَ','l-laha','Allah'),
        ('عَلَىٰ','ʿalā','(is) on'),
        ('كُلِّ','kulli','every'),
        ('شَىْءٍۢ','shayin','thing'),
        ('قَدِيرٌۭ','qadīrun','All-Powerful'),
    ],
    '2:21': [
        ('يَـٰٓأَيُّهَا','yāayyuhā','O'),
        ('ٱلنَّاسُ','l-nāsu','mankind'),
        ('ٱعْبُدُوا۟','uʿ\'budū','worship'),
        ('رَبَّكُمُ','rabbakumu','your Lord'),
        ('ٱلَّذِى','alladhī','the One Who'),
        ('خَلَقَكُمْ','khalaqakum','created you'),
        ('وَٱلَّذِينَ','wa-alladhīna','and those'),
        ('مِن','min','from'),
        ('قَبْلِكُمْ','qablikum','before you'),
        ('لَعَلَّكُمْ','laʿallakum','so that you may'),
        ('تَتَّقُونَ','tattaqūna','become righteous'),
    ],
    '2:22': [
        ('ٱلَّذِى','alladhī','The One Who'),
        ('جَعَلَ','jaʿala','made'),
        ('لَكُمُ','lakumu','for you'),
        ('ٱلْأَرْضَ','l-arḍa','the earth'),
        ('فِرَٰشًۭا','firāshan','a resting place'),
        ('وَٱلسَّمَآءَ','wal-samāa','and the sky'),
        ('بِنَآءًۭ','bināan','a canopy'),
        ('وَأَنزَلَ','wa-anzala','and sent down'),
        ('مِنَ','mina','from'),
        ('ٱلسَّمَآءِ','l-samāi','the sky'),
        ('مَآءًۭ','māan','water'),
        ('فَأَخْرَجَ','fa-akhraja','then brought forth'),
        ('بِهِۦ','bihi','therewith'),
        ('مِنَ','mina','[of]'),
        ('ٱلثَّمَرَٰتِ','l-thamarāti','the fruits'),
        ('رِزْقًۭا','riz\'qan','(as) provision'),
        ('لَّكُمْ ۖ','lakum','for you'),
        ('فَلَا','falā','So (do) not'),
        ('تَجْعَلُوا۟','tajʿalū','set up'),
        ('لِلَّهِ','lillahi','to Allah'),
        ('أَندَادًۭا','andādan','rivals'),
        ('وَأَنتُمْ','wa-antum','while you'),
        ('تَعْلَمُونَ','taʿlamūna','[you] know'),
    ],
    '2:23': [
        ('وَإِن','wa-in','And if'),
        ('كُنتُمْ','kuntum','you are'),
        ('فِى','fī','in'),
        ('رَيْبٍۢ','raybin','doubt'),
        ('مِّمَّا','mimmā','about what'),
        ('نَزَّلْنَا','nazzalnā','We have revealed'),
        ('عَلَىٰ','ʿalā','to'),
        ('عَبْدِنَا','ʿabdinā','Our slave'),
        ('فَأْتُوا۟','fatū','then produce'),
        ('بِسُورَةٍۢ','bisūratin','a chapter'),
        ('مِّن','min','[of]'),
        ('مِّثْلِهِۦ','mith\'lihi','like it'),
        ('وَٱدْعُوا۟','wa-id\'ʿū','and call'),
        ('شُهَدَآءَكُم','shuhadāakum','your witnesses'),
        ('مِّن','min','from'),
        ('دُونِ','dūni','other than'),
        ('ٱللَّهِ','l-lahi','Allah'),
        ('إِن','in','if'),
        ('كُنتُمْ','kuntum','you are'),
        ('صَـٰدِقِينَ','ṣādiqīna','truthful'),
    ],
    '2:24': [
        ('فَإِن','fa-in','But if'),
        ('لَّمْ','lam','not'),
        ('تَفْعَلُوا۟','tafʿalū','you do'),
        ('وَلَن','walan','and never'),
        ('تَفْعَلُوا۟','tafʿalū','will you do'),
        ('فَٱتَّقُوا۟','fa-ittaqū','then fear'),
        ('ٱلنَّارَ','l-nāra','the Fire'),
        ('ٱلَّتِى','allatī','whose'),
        ('وَقُودُهَا','waqūduhā','[its] fuel'),
        ('ٱلنَّاسُ','l-nāsu','(is) [the] men'),
        ('وَٱلْحِجَارَةُ ۖ','wal-ḥijāratu','and [the] stones'),
        ('أُعِدَّتْ','uʿiddat','prepared'),
        ('لِلْكَـٰفِرِينَ','lil\'kāfirīna','for the disbelievers'),
    ],
    '2:25': [
        ('وَبَشِّرِ','wabashiri','And give good news'),
        ('ٱلَّذِينَ','alladhīna','(to) those who'),
        ('ءَامَنُوا۟','āmanū','believe'),
        ('وَعَمِلُوا۟','waʿamilū','and do'),
        ('ٱلصَّـٰلِحَـٰتِ','l-ṣāliḥāti','[the] righteous deeds'),
        ('أَنَّ','anna','that'),
        ('لَهُمْ','lahum','for them'),
        ('جَنَّـٰتٍۢ','jannātin','(will be) Gardens'),
        ('تَجْرِى','tajrī','flow'),
        ('مِن','min','[from]'),
        ('تَحْتِهَا','taḥtihā','under them'),
        ('ٱلْأَنْهَـٰرُ ۖ','l-anhāru','the rivers'),
        ('كُلَّمَا','kullamā','Every time'),
        ('رُزِقُوا۟','ruziqū','they are provided'),
        ('مِنْهَا','min\'hā','therefrom'),
        ('مِن','min','of'),
        ('ثَمَرَةٍۢ','thamaratin','fruit'),
        ('رِّزْقًۭا ۙ','riz\'qan','(as) provision'),
        ('قَالُوا۟','qālū','they (will) say'),
        ('هَـٰذَا','hādhā','This (is)'),
        ('ٱلَّذِى','alladhī','the one which'),
        ('رُزِقْنَا','ruziq\'nā','we were provided'),
        ('مِن','min','from'),
        ('قَبْلُ ۖ','qablu','before'),
        ('وَأُتُوا۟','wa-utū','And they will be given'),
        ('بِهِۦ','bihi','therefrom'),
        ('مُتَشَـٰبِهًۭا ۖ','mutashābihan','(things) in resemblance'),
        ('وَلَهُمْ','walahum','And for them'),
        ('فِيهَآ','fīhā','therein'),
        ('أَزْوَٰجٌۭ','azwājun','spouses'),
        ('مُّطَهَّرَةٌۭ ۖ','muṭahharatun','purified'),
        ('وَهُمْ','wahum','and they'),
        ('فِيهَا','fīhā','therein'),
        ('خَـٰلِدُونَ','khālidūna','(will) abide forever'),
    ],
    '2:26': [
        ('۞ إِنَّ','inna','Indeed'),
        ('ٱللَّهَ','l-laha','Allah'),
        ('لَا','lā','(is) not'),
        ('يَسْتَحْىِۦٓ','yastaḥyī','ashamed'),
        ('أَن','an','to'),
        ('يَضْرِبَ','yaḍriba','set forth'),
        ('مَثَلًۭا','mathalan','an example'),
        ('مَّا','mā','(like) even'),
        ('بَعُوضَةًۭ','baʿūḍatan','(of) a mosquito'),
        ('فَمَا','famā','and (even) something'),
        ('فَوْقَهَا ۚ','fawqahā','above it'),
        ('فَأَمَّا','fa-ammā','Then as for'),
        ('ٱلَّذِينَ','alladhīna','those who'),
        ('ءَامَنُوا۟','āmanū','believed'),
        ('فَيَعْلَمُونَ','fayaʿlamūna','[thus] they will know'),
        ('أَنَّهُ','annahu','that it'),
        ('ٱلْحَقُّ','l-ḥaqu','(is) the truth'),
        ('مِن','min','from'),
        ('رَّبِّهِمْ ۖ','rabbihim','their Lord'),
        ('وَأَمَّا','wa-ammā','And as for'),
        ('ٱلَّذِينَ','alladhīna','those who'),
        ('كَفَرُوا۟','kafarū','disbelieved'),
        ('فَيَقُولُونَ','fayaqūlūna','[thus] they will say'),
        ('مَاذَآ','mādhā','what'),
        ('أَرَادَ','arāda','(did) intend'),
        ('ٱللَّهُ','l-lahu','Allah'),
        ('بِهَـٰذَا','bihādhā','by this'),
        ('مَثَلًۭا ۘ','mathalan','example'),
        ('يُضِلُّ','yuḍillu','He lets go astray'),
        ('بِهِۦ','bihi','by it'),
        ('كَثِيرًۭا','kathīran','many'),
        ('وَيَهْدِى','wayahdī','and He guides'),
        ('بِهِۦ','bihi','by it'),
        ('كَثِيرًۭا ۚ','kathīran','many'),
        ('وَمَا','wamā','And not'),
        ('يُضِلُّ','yuḍillu','He lets go astray'),
        ('بِهِۦٓ','bihi','by it'),
        ('إِلَّا','illā','except'),
        ('ٱلْفَـٰسِقِينَ','l-fāsiqīna','the defiantly disobedient'),
    ],
    '2:27': [
        ('ٱلَّذِينَ','alladhīna','Those who'),
        ('يَنقُضُونَ','yanquḍūna','break'),
        ('عَهْدَ','ʿahda','(the) Covenant'),
        ('ٱللَّهِ','l-lahi','(of) Allah'),
        ('مِنۢ','min','from'),
        ('بَعْدِ','baʿdi','after'),
        ('مِيثَـٰقِهِۦ','mīthāqihi','its ratification'),
        ('وَيَقْطَعُونَ','wayaqṭaʿūna','and [they] cut'),
        ('مَآ','mā','what'),
        ('أَمَرَ','amara','has ordered'),
        ('ٱللَّهُ','l-lahu','Allah'),
        ('بِهِۦٓ','bihi','it'),
        ('أَن','an','to'),
        ('يُوصَلَ','yūṣala','be joined'),
        ('وَيُفْسِدُونَ','wayuf\'sidūna','and [they] spread corruption'),
        ('فِى','fī','in'),
        ('ٱلْأَرْضِ ۚ','l-arḍi','the earth'),
        ('أُو۟لَـٰٓئِكَ','ulāika','Those'),
        ('هُمُ','humu','they'),
        ('ٱلْخَـٰسِرُونَ','l-khāsirūna','(are) the losers'),
    ],
    '2:28': [
        ('كَيْفَ','kayfa','How'),
        ('تَكْفُرُونَ','takfurūna','(can) you disbelieve'),
        ('بِٱللَّهِ','bil-lahi','in Allah'),
        ('وَكُنتُمْ','wakuntum','While you were'),
        ('أَمْوَٰتًۭا','amwātan','dead'),
        ('فَأَحْيَـٰكُمْ ۖ','fa-aḥyākum','then He gave you life'),
        ('ثُمَّ','thumma','then'),
        ('يُمِيتُكُمْ','yumītukum','He will cause you to die'),
        ('ثُمَّ','thumma','then'),
        ('يُحْيِيكُمْ','yuḥ\'yīkum','He will give you life'),
        ('ثُمَّ','thumma','then'),
        ('إِلَيْهِ','ilayhi','to Him'),
        ('تُرْجَعُونَ','tur\'jaʿūna','you will be returned'),
    ],
    '2:29': [
        ('هُوَ','huwa','He'),
        ('ٱلَّذِى','alladhī','(is) the One Who'),
        ('خَلَقَ','khalaqa','created'),
        ('لَكُم','lakum','for you'),
        ('مَّا','mā','what'),
        ('فِى','fī','(is) in'),
        ('ٱلْأَرْضِ','l-arḍi','the earth'),
        ('جَمِيعًۭا','jamīʿan','all'),
        ('ثُمَّ','thumma','Moreover'),
        ('ٱسْتَوَىٰٓ','is\'tawā','He turned'),
        ('إِلَى','ilā','to'),
        ('ٱلسَّمَآءِ','l-samāi','the heaven'),
        ('فَسَوَّىٰهُنَّ','fasawwāhunna','and fashioned them'),
        ('سَبْعَ','sabʿa','seven'),
        ('سَمَـٰوَٰتٍۢ ۚ','samāwātin','heavens'),
        ('وَهُوَ','wahuwa','And He'),
        ('بِكُلِّ','bikulli','of every'),
        ('شَىْءٍ','shayin','thing'),
        ('عَلِيمٌۭ','ʿalīmun','(is) All-Knowing'),
    ],
    '2:30': [
        ('وَإِذْ','wa-idh','And when'),
        ('قَالَ','qāla','said'),
        ('رَبُّكَ','rabbuka','your Lord'),
        ('لِلْمَلَـٰٓئِكَةِ','lil\'malāikati','to the angels'),
        ('إِنِّى','innī','Indeed, I (am)'),
        ('جَاعِلٌۭ','jāʿilun','going to place'),
        ('فِى','fī','in'),
        ('ٱلْأَرْضِ','l-arḍi','the earth'),
        ('خَلِيفَةًۭ ۖ','khalīfatan','a vicegerent'),
        ('قَالُوٓا۟','qālū','they said'),
        ('أَتَجْعَلُ','atajʿalu','Will You place'),
        ('فِيهَا','fīhā','in it'),
        ('مَن','man','(one) who'),
        ('يُفْسِدُ','yuf\'sidu','will spread corruption'),
        ('فِيهَا','fīhā','in it'),
        ('وَيَسْفِكُ','wayasfiku','and will shed'),
        ('ٱلدِّمَآءَ','l-dimāa','[the] blood[s]'),
        ('وَنَحْنُ','wanaḥnu','while we'),
        ('نُسَبِّحُ','nusabbiḥu','[we] glorify (You)'),
        ('بِحَمْدِكَ','biḥamdika','with Your praises'),
        ('وَنُقَدِّسُ','wanuqaddisu','and we sanctify'),
        ('لَكَ ۖ','laka','[to] You'),
        ('قَالَ','qāla','He said'),
        ('إِنِّىٓ','innī','Indeed, I'),
        ('أَعْلَمُ','aʿlamu','[I] know'),
        ('مَا','mā','what'),
        ('لَا','lā','not'),
        ('تَعْلَمُونَ','taʿlamūna','you know'),
    ],
    '2:31': [
        ('وَعَلَّمَ','waʿallama','And He taught'),
        ('ءَادَمَ','ādama','Adam'),
        ('ٱلْأَسْمَآءَ','l-asmāa','the names '),
        ('كُلَّهَا','kullahā','all of them'),
        ('ثُمَّ','thumma','Then'),
        ('عَرَضَهُمْ','ʿaraḍahum','He displayed them'),
        ('عَلَى','ʿalā','to'),
        ('ٱلْمَلَـٰٓئِكَةِ','l-malāikati','the angels'),
        ('فَقَالَ','faqāla','then He said'),
        ('أَنۢبِـُٔونِى','anbiūnī','Inform Me'),
        ('بِأَسْمَآءِ','bi-asmāi','of (the) names'),
        ('هَـٰٓؤُلَآءِ','hāulāi','(of) these'),
        ('إِن','in','if'),
        ('كُنتُمْ','kuntum','you are'),
        ('صَـٰدِقِينَ','ṣādiqīna','truthful'),
    ],
    '2:32': [
        ('قَالُوا۟','qālū','They said'),
        ('سُبْحَـٰنَكَ','sub\'ḥānaka','Glory be to You'),
        ('لَا','lā','No'),
        ('عِلْمَ','ʿil\'ma','knowledge'),
        ('لَنَآ','lanā','(is) for us'),
        ('إِلَّا','illā','except'),
        ('مَا','mā','what'),
        ('عَلَّمْتَنَآ ۖ','ʿallamtanā','You have taught us'),
        ('إِنَّكَ','innaka','Indeed You'),
        ('أَنتَ','anta','You'),
        ('ٱلْعَلِيمُ','l-ʿalīmu','(are) the All-Knowing'),
        ('ٱلْحَكِيمُ','l-ḥakīmu','the All-Wise'),
    ],
    '2:33': [
        ('قَالَ','qāla','He said'),
        ('يَـٰٓـَٔادَمُ','yāādamu','O Adam'),
        ('أَنۢبِئْهُم','anbi\'hum','Inform them'),
        ('بِأَسْمَآئِهِمْ ۖ','bi-asmāihim','of their names'),
        ('فَلَمَّآ','falammā','And when'),
        ('أَنۢبَأَهُم','anba-ahum','he had informed them'),
        ('بِأَسْمَآئِهِمْ','bi-asmāihim','of their names'),
        ('قَالَ','qāla','He said'),
        ('أَلَمْ','alam','Did not'),
        ('أَقُل','aqul','I say'),
        ('لَّكُمْ','lakum','to you'),
        ('إِنِّىٓ','innī','Indeed, I'),
        ('أَعْلَمُ','aʿlamu','[I] know'),
        ('غَيْبَ','ghayba','(the) unseen'),
        ('ٱلسَّمَـٰوَٰتِ','l-samāwāti','(of) the heavens'),
        ('وَٱلْأَرْضِ','wal-arḍi','and the earth'),
        ('وَأَعْلَمُ','wa-aʿlamu','and I know'),
        ('مَا','mā','what'),
        ('تُبْدُونَ','tub\'dūna','you reveal'),
        ('وَمَا','wamā','and what'),
        ('كُنتُمْ','kuntum','you [were]'),
        ('تَكْتُمُونَ','taktumūna','conceal'),
    ],
    '2:34': [
        ('وَإِذْ','wa-idh','And when'),
        ('قُلْنَا','qul\'nā','We said'),
        ('لِلْمَلَـٰٓئِكَةِ','lil\'malāikati','to the angels'),
        ('ٱسْجُدُوا۟','us\'judū','Prostrate'),
        ('لِـَٔادَمَ','liādama','to Adam'),
        ('فَسَجَدُوٓا۟','fasajadū','[so] they prostrated'),
        ('إِلَّآ','illā','except'),
        ('إِبْلِيسَ','ib\'līsa','Iblis'),
        ('أَبَىٰ','abā','He refused'),
        ('وَٱسْتَكْبَرَ','wa-is\'takbara','and was arrogant'),
        ('وَكَانَ','wakāna','and became'),
        ('مِنَ','mina','of'),
        ('ٱلْكَـٰفِرِينَ','l-kāfirīna','the disbelievers'),
    ],
    '2:35': [
        ('وَقُلْنَا','waqul\'nā','And We said'),
        ('يَـٰٓـَٔادَمُ','yāādamu','O Adam'),
        ('ٱسْكُنْ','us\'kun','Dwell'),
        ('أَنتَ','anta','you'),
        ('وَزَوْجُكَ','wazawjuka','and your spouse'),
        ('ٱلْجَنَّةَ','l-janata','(in) Paradise'),
        ('وَكُلَا','wakulā','and [you both] eat'),
        ('مِنْهَا','min\'hā','from it'),
        ('رَغَدًا','raghadan','freely'),
        ('حَيْثُ','ḥaythu','(from) wherever'),
        ('شِئْتُمَا','shi\'tumā','you [both] wish'),
        ('وَلَا','walā','But do not'),
        ('تَقْرَبَا','taqrabā','[you two] approach'),
        ('هَـٰذِهِ','hādhihi','this'),
        ('ٱلشَّجَرَةَ','l-shajarata','[the] tree'),
        ('فَتَكُونَا','fatakūnā','lest you [both] be'),
        ('مِنَ','mina','of'),
        ('ٱلظَّـٰلِمِينَ','l-ẓālimīna','the wrongdoers'),
    ],
    '2:36': [
        ('فَأَزَلَّهُمَا','fa-azallahumā','Then made [both of] them slip'),
        ('ٱلشَّيْطَـٰنُ','l-shayṭānu','the Shaitaan'),
        ('عَنْهَا','ʿanhā','from it'),
        ('فَأَخْرَجَهُمَا','fa-akhrajahumā','and he got [both of] them out'),
        ('مِمَّا','mimmā','from what'),
        ('كَانَا','kānā','they [both] were'),
        ('فِيهِ ۖ','fīhi','in [it]'),
        ('وَقُلْنَا','waqul\'nā','And We said'),
        ('ٱهْبِطُوا۟','ih\'biṭū','Go down (all of you)'),
        ('بَعْضُكُمْ','baʿḍukum','some of you'),
        ('لِبَعْضٍ','libaʿḍin','to others'),
        ('عَدُوٌّۭ ۖ','ʿaduwwun','(as) enemy'),
        ('وَلَكُمْ','walakum','and for you'),
        ('فِى','fī','in'),
        ('ٱلْأَرْضِ','l-arḍi','the earth'),
        ('مُسْتَقَرٌّۭ','mus\'taqarrun','(is) a dwelling place'),
        ('وَمَتَـٰعٌ','wamatāʿun','and a provision'),
        ('إِلَىٰ','ilā','for'),
        ('حِينٍۢ','ḥīnin','a period'),
    ],
    '2:37': [
        ('فَتَلَقَّىٰٓ','fatalaqqā','Then received'),
        ('ءَادَمُ','ādamu','Adam'),
        ('مِن','min','from'),
        ('رَّبِّهِۦ','rabbihi','his Lord'),
        ('كَلِمَـٰتٍۢ','kalimātin','words'),
        ('فَتَابَ','fatāba','So (his Lord) turned'),
        ('عَلَيْهِ ۚ','ʿalayhi','towards him'),
        ('إِنَّهُۥ','innahu','Indeed He'),
        ('هُوَ','huwa','He'),
        ('ٱلتَّوَّابُ','l-tawābu','(is) the Oft-returning (to mercy)'),
        ('ٱلرَّحِيمُ','l-raḥīmu','the Most Merciful'),
    ],
    '2:38': [
        ('قُلْنَا','qul\'nā','We said'),
        ('ٱهْبِطُوا۟','ih\'biṭū','Go down'),
        ('مِنْهَا','min\'hā','from it'),
        ('جَمِيعًۭا ۖ','jamīʿan','all (of you)'),
        ('فَإِمَّا','fa-immā','and when'),
        ('يَأْتِيَنَّكُم','yatiyannakum','comes to you'),
        ('مِّنِّى','minnī','from Me'),
        ('هُدًۭى','hudan','Guidance'),
        ('فَمَن','faman','then whoever'),
        ('تَبِعَ','tabiʿa','follows'),
        ('هُدَاىَ','hudāya','My Guidance'),
        ('فَلَا','falā','[then] no'),
        ('خَوْفٌ','khawfun','fear'),
        ('عَلَيْهِمْ','ʿalayhim','(will be) on them'),
        ('وَلَا','walā','and not'),
        ('هُمْ','hum','they'),
        ('يَحْزَنُونَ','yaḥzanūna','will grieve'),
    ],
    '2:39': [
        ('وَٱلَّذِينَ','wa-alladhīna','And those'),
        ('كَفَرُوا۟','kafarū','who disbelieve[d]'),
        ('وَكَذَّبُوا۟','wakadhabū','and deny'),
        ('بِـَٔايَـٰتِنَآ','biāyātinā','Our Signs'),
        ('أُو۟لَـٰٓئِكَ','ulāika','those'),
        ('أَصْحَـٰبُ','aṣḥābu','(are the) companions'),
        ('ٱلنَّارِ ۖ','l-nāri','(of) the Fire'),
        ('هُمْ','hum','they'),
        ('فِيهَا','fīhā','in it'),
        ('خَـٰلِدُونَ','khālidūna','(will) abide forever'),
    ],
    '2:40': [
        ('يَـٰبَنِىٓ','yābanī','O Children'),
        ('إِسْرَٰٓءِيلَ','is\'rāīla','(of) Israel'),
        ('ٱذْكُرُوا۟','udh\'kurū','Remember'),
        ('نِعْمَتِىَ','niʿ\'matiya','My Favor'),
        ('ٱلَّتِىٓ','allatī','which'),
        ('أَنْعَمْتُ','anʿamtu','I bestowed'),
        ('عَلَيْكُمْ','ʿalaykum','upon you'),
        ('وَأَوْفُوا۟','wa-awfū','and fulfill'),
        ('بِعَهْدِىٓ','biʿahdī','My Covenant'),
        ('أُوفِ','ūfi','I will fulfill'),
        ('بِعَهْدِكُمْ','biʿahdikum','your covenant'),
        ('وَإِيَّـٰىَ','wa-iyyāya','and Me Alone'),
        ('فَٱرْهَبُونِ','fa-ir\'habūni','fear [Me]'),
    ],
    '2:41': [
        ('وَءَامِنُوا۟','waāminū','And believe'),
        ('بِمَآ','bimā','in what'),
        ('أَنزَلْتُ','anzaltu','I have sent down'),
        ('مُصَدِّقًۭا','muṣaddiqan','confirming'),
        ('لِّمَا','limā','that which'),
        ('مَعَكُمْ','maʿakum','(is) with you'),
        ('وَلَا','walā','and (do) not'),
        ('تَكُونُوٓا۟','takūnū','be'),
        ('أَوَّلَ','awwala','(the) first'),
        ('كَافِرٍۭ','kāfirin','disbeliever'),
        ('بِهِۦ ۖ','bihi','of it'),
        ('وَلَا','walā','And (do) not'),
        ('تَشْتَرُوا۟','tashtarū','exchange'),
        ('بِـَٔايَـٰتِى','biāyātī','My Signs (for)'),
        ('ثَمَنًۭا','thamanan','a price'),
        ('قَلِيلًۭا','qalīlan','small'),
        ('وَإِيَّـٰىَ','wa-iyyāya','and Me Alone'),
        ('فَٱتَّقُونِ','fa-ittaqūni','fear [Me]'),
    ],
    '2:42': [
        ('وَلَا','walā','And (do) not'),
        ('تَلْبِسُوا۟','talbisū','mix'),
        ('ٱلْحَقَّ','l-ḥaqa','the Truth'),
        ('بِٱلْبَـٰطِلِ','bil-bāṭili','with [the] falsehood'),
        ('وَتَكْتُمُوا۟','wataktumū','and conceal'),
        ('ٱلْحَقَّ','l-ḥaqa','the Truth'),
        ('وَأَنتُمْ','wa-antum','while you'),
        ('تَعْلَمُونَ','taʿlamūna','[you] know'),
    ],
    '2:43': [
        ('وَأَقِيمُوا۟','wa-aqīmū','And establish'),
        ('ٱلصَّلَوٰةَ','l-ṣalata','the prayer'),
        ('وَءَاتُوا۟','waātū','and give'),
        ('ٱلزَّكَوٰةَ','l-zakata','zakah'),
        ('وَٱرْكَعُوا۟','wa-ir\'kaʿū','and bow down'),
        ('مَعَ','maʿa','with'),
        ('ٱلرَّٰكِعِينَ','l-rākiʿīna','those who bow down'),
    ],
    '2:44': [
        ('۞ أَتَأْمُرُونَ','atamurūna','Do you order'),
        ('ٱلنَّاسَ','l-nāsa','[the] people'),
        ('بِٱلْبِرِّ','bil-biri','[the] righteousness'),
        ('وَتَنسَوْنَ','watansawna','and you forget'),
        ('أَنفُسَكُمْ','anfusakum','yourselves'),
        ('وَأَنتُمْ','wa-antum','while you'),
        ('تَتْلُونَ','tatlūna','[you] recite'),
        ('ٱلْكِتَـٰبَ ۚ','l-kitāba','the Book'),
        ('أَفَلَا','afalā','Then, will not'),
        ('تَعْقِلُونَ','taʿqilūna','you use reason'),
    ],
    '2:45': [
        ('وَٱسْتَعِينُوا۟','wa-is\'taʿīnū','And seek help'),
        ('بِٱلصَّبْرِ','bil-ṣabri','through patience'),
        ('وَٱلصَّلَوٰةِ ۚ','wal-ṣalati','and the prayer'),
        ('وَإِنَّهَا','wa-innahā','and indeed, it'),
        ('لَكَبِيرَةٌ','lakabīratun','(is) surely difficult'),
        ('إِلَّا','illā','except'),
        ('عَلَى','ʿalā','on'),
        ('ٱلْخَـٰشِعِينَ','l-khāshiʿīna','the humble ones'),
    ],
    '2:46': [
        ('ٱلَّذِينَ','alladhīna','Those who'),
        ('يَظُنُّونَ','yaẓunnūna','believe'),
        ('أَنَّهُم','annahum','that they'),
        ('مُّلَـٰقُوا۟','mulāqū','will meet'),
        ('رَبِّهِمْ','rabbihim','their Lord'),
        ('وَأَنَّهُمْ','wa-annahum','and that they'),
        ('إِلَيْهِ','ilayhi','to Him'),
        ('رَٰجِعُونَ','rājiʿūna','will return'),
    ],
    '2:47': [
        ('يَـٰبَنِىٓ','yābanī','O Children'),
        ('إِسْرَٰٓءِيلَ','is\'rāīla','(of) Israel'),
        ('ٱذْكُرُوا۟','udh\'kurū','Remember'),
        ('نِعْمَتِىَ','niʿ\'matiya','My Favor'),
        ('ٱلَّتِىٓ','allatī','which'),
        ('أَنْعَمْتُ','anʿamtu','I bestowed'),
        ('عَلَيْكُمْ','ʿalaykum','upon you'),
        ('وَأَنِّى','wa-annī','and that I'),
        ('فَضَّلْتُكُمْ','faḍḍaltukum','[I] preferred you'),
        ('عَلَى','ʿalā','over'),
        ('ٱلْعَـٰلَمِينَ','l-ʿālamīna','the worlds'),
    ],
    '2:48': [
        ('وَٱتَّقُوا۟','wa-ittaqū','And fear'),
        ('يَوْمًۭا','yawman','a day'),
        ('لَّا','lā','(will) not'),
        ('تَجْزِى','tajzī','avail'),
        ('نَفْسٌ','nafsun','any soul'),
        ('عَن','ʿan','for'),
        ('نَّفْسٍۢ','nafsin','(another) soul'),
        ('شَيْـًۭٔا','shayan','anything'),
        ('وَلَا','walā','and not'),
        ('يُقْبَلُ','yuq\'balu','will be accepted'),
        ('مِنْهَا','min\'hā','from it'),
        ('شَفَـٰعَةٌۭ','shafāʿatun','any intercession'),
        ('وَلَا','walā','and not'),
        ('يُؤْخَذُ','yu\'khadhu','will be taken'),
        ('مِنْهَا','min\'hā','from it'),
        ('عَدْلٌۭ','ʿadlun','a compensation'),
        ('وَلَا','walā','and not'),
        ('هُمْ','hum','they'),
        ('يُنصَرُونَ','yunṣarūna','will be helped'),
    ],
    '2:49': [
        ('وَإِذْ','wa-idh','And when'),
        ('نَجَّيْنَـٰكُم','najjaynākum','We saved you'),
        ('مِّنْ','min','from'),
        ('ءَالِ','āli','(the) people'),
        ('فِرْعَوْنَ','fir\'ʿawna','(of) Firaun'),
        ('يَسُومُونَكُمْ','yasūmūnakum','(who were) afflicting you (with)'),
        ('سُوٓءَ','sūa','horrible'),
        ('ٱلْعَذَابِ','l-ʿadhābi','torment'),
        ('يُذَبِّحُونَ','yudhabbiḥūna','slaughtering'),
        ('أَبْنَآءَكُمْ','abnāakum','your sons'),
        ('وَيَسْتَحْيُونَ','wayastaḥyūna','and letting live'),
        ('نِسَآءَكُمْ ۚ','nisāakum','your women'),
        ('وَفِى','wafī','And in'),
        ('ذَٰلِكُم','dhālikum','that'),
        ('بَلَآءٌۭ','balāon','(was) a trial'),
        ('مِّن','min','from'),
        ('رَّبِّكُمْ','rabbikum','your Lord'),
        ('عَظِيمٌۭ','ʿaẓīmun','great'),
    ],
    '2:50': [
        ('وَإِذْ','wa-idh','And when'),
        ('فَرَقْنَا','faraqnā','We parted'),
        ('بِكُمُ','bikumu','for you'),
        ('ٱلْبَحْرَ','l-baḥra','the sea'),
        ('فَأَنجَيْنَـٰكُمْ','fa-anjaynākum','then We saved you'),
        ('وَأَغْرَقْنَآ','wa-aghraqnā','and We drowned'),
        ('ءَالَ','āla','(the) people'),
        ('فِرْعَوْنَ','fir\'ʿawna','(of) Firaun'),
        ('وَأَنتُمْ','wa-antum','while you'),
        ('تَنظُرُونَ','tanẓurūna','(were) looking'),
    ],
}

EXTRA_MEANINGS = {
    '2:14': 'And when they meet those who believe, they say, "We believe"; but when they are alone with their evil ones, they say, "Indeed, we are with you; we were only mockers."',
    '2:15': '[But] Allāh mocks them and prolongs them in their transgression [while] they wander blindly.',
    '2:16': 'Those are the ones who have purchased error [in exchange] for guidance, so their transaction has brought no profit, nor were they guided.',
    '2:17': 'Their example is that of one who kindled a fire, but when it illuminated what was around him, Allāh took away their light and left them in darkness [so] they could not see.',
    '2:18': 'Deaf, dumb and blind - so they will not return [to the right path].',
    '2:19': 'Or [it is] like a rainstorm from the sky within which is darkness, thunder and lightning. They put their fingers in their ears against the thunderclaps in dread of death. But Allāh is encompassing1 of the disbelievers.',
    '2:20': 'The lightning almost snatches away their sight. Every time it lights [the way] for them, they walk therein; but when darkness comes over them, they stand [still]. And if Allāh had willed, He could have taken away their hearing and their sight. Indeed, Allāh is over all things competent.',
    '2:21': 'O mankind, worship your Lord, who created you and those before you, that you may become righteous -',
    '2:22': '[He] who made for you the earth a bed [spread out] and the sky a ceiling and sent down from the sky, rain and brought forth thereby fruits as provision for you. So do not attribute to Allāh equals while you know [that there is nothing similar to Him].',
    '2:23': 'And if you are in doubt about what We have sent down [i.e., the Qur’ān] upon Our Servant [i.e., Prophet Muḥammad (ﷺ)], then produce a sūrah the like thereof and call upon your witnesses [i.e., supporters] other than Allāh, if you should be truthful.',
    '2:24': 'But if you do not - and you will never be able to - then fear the Fire, whose fuel is people and stones, prepared for the disbelievers.',
    '2:25': 'And give good tidings to those who believe and do righteous deeds that they will have gardens [in Paradise] beneath which rivers flow. Whenever they are provided with a provision of fruit therefrom, they will say, "This is what we were provided with before." And it is given to them in likeness. And they will have therein purified spouses, and they will abide therein eternally.',
    '2:26': 'Indeed, Allāh is not timid to present an example - that of a mosquito or what is smaller1 than it. And those who have believed know that it is the truth from their Lord. But as for those who disbelieve, they say, "What did Allāh intend by this as an example?" He misleads many thereby and guides many thereby. And He misleads not except the defiantly disobedient,',
    '2:27': 'Who break the covenant of Allāh after contracting it and sever that which Allāh has ordered to be joined and cause corruption on earth. It is those who are the losers.',
    '2:28': 'How can you disbelieve in Allāh when you were lifeless and He brought you to life; then He will cause you to die, then He will bring you [back] to life, and then to Him you will be returned.',
    '2:29': 'It is He who created for you all of that which is on the earth. Then He directed Himself1 to the heaven, [His being above all creation], and made them seven heavens, and He is Knowing of all things.',
    '2:30': 'And [mention, O Muḥammad], when your Lord said to the angels, "Indeed, I will make upon the earth a successive authority."1 They said, "Will You place upon it one who causes corruption therein and sheds blood, while we exalt You with praise and declare Your perfection?"2 He [Allāh] said, "Indeed, I know that which you do not know."',
    '2:31': 'And He taught Adam the names - all of them. Then He showed them to the angels and said, "Inform Me of the names of these, if you are truthful."',
    '2:32': 'They said, "Exalted are You; we have no knowledge except what You have taught us. Indeed, it is You who is the Knowing,1 the Wise."2',
    '2:33': 'He said, "O Adam, inform them of their names." And when he had informed them of their names, He said, "Did I not tell you that I know the unseen [aspects] of the heavens and the earth? And I know what you reveal and what you have concealed."',
    '2:34': 'And [mention] when We said to the angels, "Prostrate before Adam"; so they prostrated, except for Iblees.1 He refused and was arrogant and became of the disbelievers.',
    '2:35': 'And We said, "O Adam, dwell, you and your wife, in Paradise and eat therefrom in [ease and] abundance from wherever you will. But do not approach this tree, lest you be among the wrongdoers."',
    '2:36': 'But Satan caused them to slip out of it and removed them from that [condition] in which they had been. And We said, "Go down, [all of you], as enemies to one another, and you will have upon the earth a place of settlement and provision for a time."',
    '2:37': 'Then Adam received from his Lord [some] words,1 and He accepted his repentance. Indeed, it is He who is the Accepting of Repentance,2 the Merciful.',
    '2:38': 'We said, "Go down from it, all of you. And when guidance comes to you from Me, whoever follows My guidance - there will be no fear concerning them, nor will they grieve.',
    '2:39': 'And those who disbelieve and deny Our signs - those will be companions of the Fire; they will abide therein eternally."',
    '2:40': 'O Children of Israel, remember My favor which I have bestowed upon you and fulfill My covenant [upon you] that I will fulfill your covenant [from Me], and be afraid of [only] Me.',
    '2:41': 'And believe in what I have sent down confirming that which is [already] with you, and be not the first to disbelieve in it. And do not exchange My signs for a small price, and fear [only] Me.',
    '2:42': 'And do not mix the truth with falsehood or conceal the truth while you know [it].',
    '2:43': 'And establish prayer and give zakāh1 and bow with those who bow [in worship and obedience].',
    '2:44': 'Do you order righteousness of the people and forget1 yourselves while you recite the Scripture? Then will you not reason?',
    '2:45': 'And seek help through patience and prayer; and indeed, it is difficult except for the humbly submissive [to Allāh]',
    '2:46': 'Who are certain that they will meet their Lord and that they will return to Him.',
    '2:47': 'O Children of Israel, remember My favor that I have bestowed upon you and that I preferred you over the worlds [i.e., peoples].',
    '2:48': 'And fear a Day when no soul will suffice for another soul1 at all, nor will intercession be accepted from it, nor will compensation be taken from it, nor will they be aided.',
    '2:49': 'And [recall] when We saved you [i.e., your forefathers] from the people of Pharaoh, who afflicted you with the worst torment, slaughtering your [newborn] sons and keeping your females alive. And in that was a great trial from your Lord.',
    '2:50': 'And [recall] when We parted the sea for you and saved you and drowned the people of Pharaoh while you were looking on.',
}
