# Auto-generated extra verse data — to be merged into generate.py
EXTRA_WORDS = {
    '2:14': [
        ('وَإِذَا','wa-idhā','And when'),
        ('لَقُوا۟','laqū','they meet'),
        ('ٱلَّذِينَ','alladhīna','those who'),
        ('ءَامَنُوا۟','āmanū','believe[d]'),
        ('قَالُوٓا۟','qālū','they say'),
        ('ءَامَنَّا','āmannā','We believe[d]'),
        ('وَإِذَا','wa-idhā','But when'),
        ('خَلَوْا۟','khalaw','they are alone'),
        ('إِلَىٰ','ilā','with'),
        ('شَيَـٰطِينِهِمْ','shayāṭīnihim','their evil ones'),
        ('قَالُوٓا۟','qālū','they say'),
        ('إِنَّا','innā','Indeed, we'),
        ('مَعَكُمْ','maʿakum','(are) with you'),
        ('إِنَّمَا','innamā','only'),
        ('نَحْنُ','naḥnu','we'),
        ('مُسْتَهْزِءُونَ','mus\'tahziūna','(are) mockers'),
    ],
    '2:15': [
        ('ٱللَّهُ','al-lahu','Allah'),
        ('يَسْتَهْزِئُ','yastahzi-u','mocks'),
        ('بِهِمْ','bihim','at them'),
        ('وَيَمُدُّهُمْ','wayamudduhum','and prolongs them'),
        ('فِى','fī','in'),
        ('طُغْيَـٰنِهِمْ','ṭugh\'yānihim','their transgression'),
        ('يَعْمَهُونَ','yaʿmahūna','they wander blindly'),
    ],
    '2:16': [
        ('أُو۟لَـٰٓئِكَ','ulāika','Those'),
        ('ٱلَّذِينَ','alladhīna','(are) the ones who'),
        ('ٱشْتَرَوُا۟','ish\'tarawū','bought'),
        ('ٱلضَّلَـٰلَةَ','l-ḍalālata','[the] astraying'),
        ('بِٱلْهُدَىٰ','bil-hudā','for [the] guidance'),
        ('فَمَا','famā','So not'),
        ('رَبِحَت','rabiḥat','profited'),
        ('تِّجَـٰرَتُهُمْ','tijāratuhum','their commerce'),
        ('وَمَا','wamā','and not'),
        ('كَانُوا۟','kānū','were they'),
        ('مُهْتَدِينَ','muh\'tadīna','guided-ones'),
    ],
    '2:17': [
        ('مَثَلُهُمْ','mathaluhum','Their example'),
        ('كَمَثَلِ','kamathali','(is) like (the) example'),
        ('ٱلَّذِى','alladhī','(of) the one who'),
        ('ٱسْتَوْقَدَ','is\'tawqada','kindled'),
        ('نَارًۭا','nāran','a fire'),
        ('فَلَمَّآ','falammā','then, when'),
        ('أَضَآءَتْ','aḍāat','it illuminated'),
        ('مَا','mā','what'),
        ('حَوْلَهُۥ','ḥawlahu','(was) around him'),
        ('ذَهَبَ','dhahaba','took away'),
        ('ٱللَّهُ','l-lahu','Allah'),
        ('بِنُورِهِمْ','binūrihim','their light'),
        ('وَتَرَكَهُمْ','watarakahum','and left them'),
        ('فِى','fī','in'),
        ('ظُلُمَـٰتٍۢ','ẓulumātin','darkness[es]'),
        ('لَّا','lā','(so) not'),
        ('يُبْصِرُونَ','yub\'ṣirūna','(do) they see'),
    ],
    '2:18': [
        ('صُمٌّۢ','ṣummun','Deaf'),
        ('بُكْمٌ','buk\'mun','dumb'),
        ('عُمْىٌۭ','ʿum\'yun','blind'),
        ('فَهُمْ','fahum','so they'),
        ('لَا','lā','not'),
        ('يَرْجِعُونَ','yarjiʿūna','[they] will not return'),
    ],
    '2:19': [
        ('أَوْ','aw','Or'),
        ('كَصَيِّبٍۢ','kaṣayyibin','like a rainstorm'),
        ('مِّنَ','mina','from'),
        ('ٱلسَّمَآءِ','l-samāi','the sky'),
        ('فِيهِ','fīhi','in it (are)'),
        ('ظُلُمَـٰتٌۭ','ẓulumātun','darkness[es]'),
        ('وَرَعْدٌۭ','waraʿdun','and thunder'),
        ('وَبَرْقٌۭ','wabarqun','and lightning'),
        ('يَجْعَلُونَ','yajʿalūna','They put'),
        ('أَصَـٰبِعَهُمْ','aṣābiʿahum','their fingers'),
        ('فِىٓ','fī','in'),
        ('ءَاذَانِهِم','ādhānihim','their ears'),
        ('مِّنَ','mina','from'),
        ('ٱلصَّوَٰعِقِ','l-ṣawāʿiqi','the thunderclaps'),
        ('حَذَرَ','ḥadhara','(in) fear (of)'),
        ('ٱلْمَوْتِ ۚ','l-mawti','[the] death'),
        ('وَٱللَّهُ','wal-lahu','And Allah'),
        ('مُحِيطٌۢ','muḥīṭun','(is) [the One Who] encompasses'),
        ('بِٱلْكَـٰفِرِينَ','bil-kāfirīna','the disbelievers'),
    ],
    '2:20': [
        ('يَكَادُ','yakādu','Almost'),
        ('ٱلْبَرْقُ','l-barqu','the lightning'),
        ('يَخْطَفُ','yakhṭafu','snatches away'),
        ('أَبْصَـٰرَهُمْ ۖ','abṣārahum','their sight'),
        ('كُلَّمَآ','kullamā','Whenever'),
        ('أَضَآءَ','aḍāa','it flashes'),
        ('لَهُم','lahum','for them'),
        ('مَّشَوْا۟','mashaw','they walk'),
        ('فِيهِ','fīhi','in it'),
        ('وَإِذَآ','wa-idhā','and when'),
        ('أَظْلَمَ','aẓlama','it darkens'),
        ('عَلَيْهِمْ','ʿalayhim','on them'),
        ('قَامُوا۟ ۚ','qāmū','they stand (still)'),
        ('وَلَوْ','walaw','And if'),
        ('شَآءَ','shāa','had willed'),
        ('ٱللَّهُ','l-lahu','Allah'),
        ('لَذَهَبَ','ladhahaba','He would certainly have taken away'),
        ('بِسَمْعِهِمْ','bisamʿihim','their hearing'),
        ('وَأَبْصَـٰرِهِمْ ۚ','wa-abṣārihim','and their sight'),
        ('إِنَّ','inna','Indeed'),
        ('ٱللَّهَ','l-laha','Allah'),
        ('عَلَىٰ','ʿalā','(is) on'),
        ('كُلِّ','kulli','every'),
        ('شَىْءٍۢ','shayin','thing'),
        ('قَدِيرٌۭ','qadīrun','All-Powerful'),
    ],
    '2:21': [
        ('يَـٰٓأَيُّهَا','yāayyuhā','O'),
        ('ٱلنَّاسُ','l-nāsu','mankind'),
        ('ٱعْبُدُوا۟','uʿ\'budū','worship'),
        ('رَبَّكُمُ','rabbakumu','your Lord'),
        ('ٱلَّذِى','alladhī','the One Who'),
        ('خَلَقَكُمْ','khalaqakum','created you'),
        ('وَٱلَّذِينَ','wa-alladhīna','and those'),
        ('مِن','min','from'),
        ('قَبْلِكُمْ','qablikum','before you'),
        ('لَعَلَّكُمْ','laʿallakum','so that you may'),
        ('تَتَّقُونَ','tattaqūna','become righteous'),
    ],
    '2:22': [
        ('ٱلَّذِى','alladhī','The One Who'),
        ('جَعَلَ','jaʿala','made'),
        ('لَكُمُ','lakumu','for you'),
        ('ٱلْأَرْضَ','l-arḍa','the earth'),
        ('فِرَٰشًۭا','firāshan','a resting place'),
        ('وَٱلسَّمَآءَ','wal-samāa','and the sky'),
        ('بِنَآءًۭ','bināan','a canopy'),
        ('وَأَنزَلَ','wa-anzala','and sent down'),
        ('مِنَ','mina','from'),
        ('ٱلسَّمَآءِ','l-samāi','the sky'),
        ('مَآءًۭ','māan','water'),
        ('فَأَخْرَجَ','fa-akhraja','then brought forth'),
        ('بِهِۦ','bihi','therewith'),
        ('مِنَ','mina','[of]'),
        ('ٱلثَّمَرَٰتِ','l-thamarāti','the fruits'),
        ('رِزْقًۭا','riz\'qan','(as) provision'),
        ('لَّكُمْ ۖ','lakum','for you'),
        ('فَلَا','falā','So (do) not'),
        ('تَجْعَلُوا۟','tajʿalū','set up'),
        ('لِلَّهِ','lillahi','to Allah'),
        ('أَندَادًۭا','andādan','rivals'),
        ('وَأَنتُمْ','wa-antum','while you'),
        ('تَعْلَمُونَ','taʿlamūna','[you] know'),
    ],
    '2:23': [
        ('وَإِن','wa-in','And if'),
        ('كُنتُمْ','kuntum','you are'),
        ('فِى','fī','in'),
        ('رَيْبٍۢ','raybin','doubt'),
        ('مِّمَّا','mimmā','about what'),
        ('نَزَّلْنَا','nazzalnā','We have revealed'),
        ('عَلَىٰ','ʿalā','to'),
        ('عَبْدِنَا','ʿabdinā','Our slave'),
        ('فَأْتُوا۟','fatū','then produce'),
        ('بِسُورَةٍۢ','bisūratin','a chapter'),
        ('مِّن','min','[of]'),
        ('مِّثْلِهِۦ','mith\'lihi','like it'),
        ('وَٱدْعُوا۟','wa-id\'ʿū','and call'),
        ('شُهَدَآءَكُم','shuhadāakum','your witnesses'),
        ('مِّن','min','from'),
        ('دُونِ','dūni','other than'),
        ('ٱللَّهِ','l-lahi','Allah'),
        ('إِن','in','if'),
        ('كُنتُمْ','kuntum','you are'),
        ('صَـٰدِقِينَ','ṣādiqīna','truthful'),
    ],
    '2:24': [
        ('فَإِن','fa-in','But if'),
        ('لَّمْ','lam','not'),
        ('تَفْعَلُوا۟','tafʿalū','you do'),
        ('وَلَن','walan','and never'),
        ('تَفْعَلُوا۟','tafʿalū','will you do'),
        ('فَٱتَّقُوا۟','fa-ittaqū','then fear'),
        ('ٱلنَّارَ','l-nāra','the Fire'),
        ('ٱلَّتِى','allatī','whose'),
        ('وَقُودُهَا','waqūduhā','[its] fuel'),
        ('ٱلنَّاسُ','l-nāsu','(is) [the] men'),
        ('وَٱلْحِجَارَةُ ۖ','wal-ḥijāratu','and [the] stones'),
        ('أُعِدَّتْ','uʿiddat','prepared'),
        ('لِلْكَـٰفِرِينَ','lil\'kāfirīna','for the disbelievers'),
    ],
    '2:25': [
        ('وَبَشِّرِ','wabashiri','And give good news'),
        ('ٱلَّذِينَ','alladhīna','(to) those who'),
        ('ءَامَنُوا۟','āmanū','believe'),
        ('وَعَمِلُوا۟','waʿamilū','and do'),
        ('ٱلصَّـٰلِحَـٰتِ','l-ṣāliḥāti','[the] righteous deeds'),
        ('أَنَّ','anna','that'),
        ('لَهُمْ','lahum','for them'),
        ('جَنَّـٰتٍۢ','jannātin','(will be) Gardens'),
        ('تَجْرِى','tajrī','flow'),
        ('مِن','min','[from]'),
        ('تَحْتِهَا','taḥtihā','under them'),
        ('ٱلْأَنْهَـٰرُ ۖ','l-anhāru','the rivers'),
        ('كُلَّمَا','kullamā','Every time'),
        ('رُزِقُوا۟','ruziqū','they are provided'),
        ('مِنْهَا','min\'hā','therefrom'),
        ('مِن','min','of'),
        ('ثَمَرَةٍۢ','thamaratin','fruit'),
        ('رِّزْقًۭا ۙ','riz\'qan','(as) provision'),
        ('قَالُوا۟','qālū','they (will) say'),
        ('هَـٰذَا','hādhā','This (is)'),
        ('ٱلَّذِى','alladhī','the one which'),
        ('رُزِقْنَا','ruziq\'nā','we were provided'),
        ('مِن','min','from'),
        ('قَبْلُ ۖ','qablu','before'),
        ('وَأُتُوا۟','wa-utū','And they will be given'),
        ('بِهِۦ','bihi','therefrom'),
        ('مُتَشَـٰبِهًۭا ۖ','mutashābihan','(things) in resemblance'),
        ('وَلَهُمْ','walahum','And for them'),
        ('فِيهَآ','fīhā','therein'),
        ('أَزْوَٰجٌۭ','azwājun','spouses'),
        ('مُّطَهَّرَةٌۭ ۖ','muṭahharatun','purified'),
        ('وَهُمْ','wahum','and they'),
        ('فِيهَا','fīhā','therein'),
        ('خَـٰلِدُونَ','khālidūna','(will) abide forever'),
    ],
    '2:26': [
        ('۞ إِنَّ','inna','Indeed'),
        ('ٱللَّهَ','l-laha','Allah'),
        ('لَا','lā','(is) not'),
        ('يَسْتَحْىِۦٓ','yastaḥyī','ashamed'),
        ('أَن','an','to'),
        ('يَضْرِبَ','yaḍriba','set forth'),
        ('مَثَلًۭا','mathalan','an example'),
        ('مَّا','mā','(like) even'),
        ('بَعُوضَةًۭ','baʿūḍatan','(of) a mosquito'),
        ('فَمَا','famā','and (even) something'),
        ('فَوْقَهَا ۚ','fawqahā','above it'),
        ('فَأَمَّا','fa-ammā','Then as for'),
        ('ٱلَّذِينَ','alladhīna','those who'),
        ('ءَامَنُوا۟','āmanū','believed'),
        ('فَيَعْلَمُونَ','fayaʿlamūna','[thus] they will know'),
        ('أَنَّهُ','annahu','that it'),
        ('ٱلْحَقُّ','l-ḥaqu','(is) the truth'),
        ('مِن','min','from'),
        ('رَّبِّهِمْ ۖ','rabbihim','their Lord'),
        ('وَأَمَّا','wa-ammā','And as for'),
        ('ٱلَّذِينَ','alladhīna','those who'),
        ('كَفَرُوا۟','kafarū','disbelieved'),
        ('فَيَقُولُونَ','fayaqūlūna','[thus] they will say'),
        ('مَاذَآ','mādhā','what'),
        ('أَرَادَ','arāda','(did) intend'),
        ('ٱللَّهُ','l-lahu','Allah'),
        ('بِهَـٰذَا','bihādhā','by this'),
        ('مَثَلًۭا ۘ','mathalan','example'),
        ('يُضِلُّ','yuḍillu','He lets go astray'),
        ('بِهِۦ','bihi','by it'),
        ('كَثِيرًۭا','kathīran','many'),
        ('وَيَهْدِى','wayahdī','and He guides'),
        ('بِهِۦ','bihi','by it'),
        ('كَثِيرًۭا ۚ','kathīran','many'),
        ('وَمَا','wamā','And not'),
        ('يُضِلُّ','yuḍillu','He lets go astray'),
        ('بِهِۦٓ','bihi','by it'),
        ('إِلَّا','illā','except'),
        ('ٱلْفَـٰسِقِينَ','l-fāsiqīna','the defiantly disobedient'),
    ],
    '2:27': [
        ('ٱلَّذِينَ','alladhīna','Those who'),
        ('يَنقُضُونَ','yanquḍūna','break'),
        ('عَهْدَ','ʿahda','(the) Covenant'),
        ('ٱللَّهِ','l-lahi','(of) Allah'),
        ('مِنۢ','min','from'),
        ('بَعْدِ','baʿdi','after'),
        ('مِيثَـٰقِهِۦ','mīthāqihi','its ratification'),
        ('وَيَقْطَعُونَ','wayaqṭaʿūna','and [they] cut'),
        ('مَآ','mā','what'),
        ('أَمَرَ','amara','has ordered'),
        ('ٱللَّهُ','l-lahu','Allah'),
        ('بِهِۦٓ','bihi','it'),
        ('أَن','an','to'),
        ('يُوصَلَ','yūṣala','be joined'),
        ('وَيُفْسِدُونَ','wayuf\'sidūna','and [they] spread corruption'),
        ('فِى','fī','in'),
        ('ٱلْأَرْضِ ۚ','l-arḍi','the earth'),
        ('أُو۟لَـٰٓئِكَ','ulāika','Those'),
        ('هُمُ','humu','they'),
        ('ٱلْخَـٰسِرُونَ','l-khāsirūna','(are) the losers'),
    ],
    '2:28': [
        ('كَيْفَ','kayfa','How'),
        ('تَكْفُرُونَ','takfurūna','(can) you disbelieve'),
        ('بِٱللَّهِ','bil-lahi','in Allah'),
        ('وَكُنتُمْ','wakuntum','While you were'),
        ('أَمْوَٰتًۭا','amwātan','dead'),
        ('فَأَحْيَـٰكُمْ ۖ','fa-aḥyākum','then He gave you life'),
        ('ثُمَّ','thumma','then'),
        ('يُمِيتُكُمْ','yumītukum','He will cause you to die'),
        ('ثُمَّ','thumma','then'),
        ('يُحْيِيكُمْ','yuḥ\'yīkum','He will give you life'),
        ('ثُمَّ','thumma','then'),
        ('إِلَيْهِ','ilayhi','to Him'),
        ('تُرْجَعُونَ','tur\'jaʿūna','you will be returned'),
    ],
    '2:29': [
        ('هُوَ','huwa','He'),
        ('ٱلَّذِى','alladhī','(is) the One Who'),
        ('خَلَقَ','khalaqa','created'),
        ('لَكُم','lakum','for you'),
        ('مَّا','mā','what'),
        ('فِى','fī','(is) in'),
        ('ٱلْأَرْضِ','l-arḍi','the earth'),
        ('جَمِيعًۭا','jamīʿan','all'),
        ('ثُمَّ','thumma','Moreover'),
        ('ٱسْتَوَىٰٓ','is\'tawā','He turned'),
        ('إِلَى','ilā','to'),
        ('ٱلسَّمَآءِ','l-samāi','the heaven'),
        ('فَسَوَّىٰهُنَّ','fasawwāhunna','and fashioned them'),
        ('سَبْعَ','sabʿa','seven'),
        ('سَمَـٰوَٰتٍۢ ۚ','samāwātin','heavens'),
        ('وَهُوَ','wahuwa','And He'),
        ('بِكُلِّ','bikulli','of every'),
        ('شَىْءٍ','shayin','thing'),
        ('عَلِيمٌۭ','ʿalīmun','(is) All-Knowing'),
    ],
    '2:30': [
        ('وَإِذْ','wa-idh','And when'),
        ('قَالَ','qāla','said'),
        ('رَبُّكَ','rabbuka','your Lord'),
        ('لِلْمَلَـٰٓئِكَةِ','lil\'malāikati','to the angels'),
        ('إِنِّى','innī','Indeed, I (am)'),
        ('جَاعِلٌۭ','jāʿilun','going to place'),
        ('فِى','fī','in'),
        ('ٱلْأَرْضِ','l-arḍi','the earth'),
        ('خَلِيفَةًۭ ۖ','khalīfatan','a vicegerent'),
        ('قَالُوٓا۟','qālū','they said'),
        ('أَتَجْعَلُ','atajʿalu','Will You place'),
        ('فِيهَا','fīhā','in it'),
        ('مَن','man','(one) who'),
        ('يُفْسِدُ','yuf\'sidu','will spread corruption'),
        ('فِيهَا','fīhā','in it'),
        ('وَيَسْفِكُ','wayasfiku','and will shed'),
        ('ٱلدِّمَآءَ','l-dimāa','[the] blood[s]'),
        ('وَنَحْنُ','wanaḥnu','while we'),
        ('نُسَبِّحُ','nusabbiḥu','[we] glorify (You)'),
        ('بِحَمْدِكَ','biḥamdika','with Your praises'),
        ('وَنُقَدِّسُ','wanuqaddisu','and we sanctify'),
        ('لَكَ ۖ','laka','[to] You'),
        ('قَالَ','qāla','He said'),
        ('إِنِّىٓ','innī','Indeed, I'),
        ('أَعْلَمُ','aʿlamu','[I] know'),
        ('مَا','mā','what'),
        ('لَا','lā','not'),
        ('تَعْلَمُونَ','taʿlamūna','you know'),
    ],
}

EXTRA_MEANINGS = {
    '2:14': 'And when they meet those who believe, they say, "We believe"; but when they are alone with their evil ones, they say, "Indeed, we are with you; we were only mockers."',
    '2:15': '[But] Allāh mocks them and prolongs them in their transgression [while] they wander blindly.',
    '2:16': 'Those are the ones who have purchased error [in exchange] for guidance, so their transaction has brought no profit, nor were they guided.',
    '2:17': 'Their example is that of one who kindled a fire, but when it illuminated what was around him, Allāh took away their light and left them in darkness [so] they could not see.',
    '2:18': 'Deaf, dumb and blind - so they will not return [to the right path].',
    '2:19': 'Or [it is] like a rainstorm from the sky within which is darkness, thunder and lightning. They put their fingers in their ears against the thunderclaps in dread of death. But Allāh is encompassing1 of the disbelievers.',
    '2:20': 'The lightning almost snatches away their sight. Every time it lights [the way] for them, they walk therein; but when darkness comes over them, they stand [still]. And if Allāh had willed, He could have taken away their hearing and their sight. Indeed, Allāh is over all things competent.',
    '2:21': 'O mankind, worship your Lord, who created you and those before you, that you may become righteous -',
    '2:22': '[He] who made for you the earth a bed [spread out] and the sky a ceiling and sent down from the sky, rain and brought forth thereby fruits as provision for you. So do not attribute to Allāh equals while you know [that there is nothing similar to Him].',
    '2:23': 'And if you are in doubt about what We have sent down [i.e., the Qur’ān] upon Our Servant [i.e., Prophet Muḥammad (ﷺ)], then produce a sūrah the like thereof and call upon your witnesses [i.e., supporters] other than Allāh, if you should be truthful.',
    '2:24': 'But if you do not - and you will never be able to - then fear the Fire, whose fuel is people and stones, prepared for the disbelievers.',
    '2:25': 'And give good tidings to those who believe and do righteous deeds that they will have gardens [in Paradise] beneath which rivers flow. Whenever they are provided with a provision of fruit therefrom, they will say, "This is what we were provided with before." And it is given to them in likeness. And they will have therein purified spouses, and they will abide therein eternally.',
    '2:26': 'Indeed, Allāh is not timid to present an example - that of a mosquito or what is smaller1 than it. And those who have believed know that it is the truth from their Lord. But as for those who disbelieve, they say, "What did Allāh intend by this as an example?" He misleads many thereby and guides many thereby. And He misleads not except the defiantly disobedient,',
    '2:27': 'Who break the covenant of Allāh after contracting it and sever that which Allāh has ordered to be joined and cause corruption on earth. It is those who are the losers.',
    '2:28': 'How can you disbelieve in Allāh when you were lifeless and He brought you to life; then He will cause you to die, then He will bring you [back] to life, and then to Him you will be returned.',
    '2:29': 'It is He who created for you all of that which is on the earth. Then He directed Himself1 to the heaven, [His being above all creation], and made them seven heavens, and He is Knowing of all things.',
    '2:30': 'And [mention, O Muḥammad], when your Lord said to the angels, "Indeed, I will make upon the earth a successive authority."1 They said, "Will You place upon it one who causes corruption therein and sheds blood, while we exalt You with praise and declare Your perfection?"2 He [Allāh] said, "Indeed, I know that which you do not know."',
}
